### PR TITLE
adds back col-xs

### PR DESCRIPTION
**Pull request by MiguelMadero**
Just out of curiosity and for the record, this PR proves that it's possible to do this and add back `col-xs-*`, that said, I'm not sure it's a good idea. I think it was terrible that bootstrap decided to break backward compatibility... but that was their decision and it might be better to keep out BS4 implementation standard. What do you think? 

Here are the docs for reference: https://v4-alpha.getbootstrap.com/layout/grid/#grid-options

### CODE REVIEW

**Comment by MiguelMadero** [comment]
@dqian-zenefits what do you think?

**Comment by dqian-zenefits** [comment]
what about having both rules so that we have the opportunity to convert back to vanilla bs4 at a later convenient date?

**Comment by MiguelMadero** [comment]
It isn't easy to do both, even if we did, that means that we would be writing new legacy code. For example, should level-funding use the new way or the old way? Is there a reason to make the old one available there?

**Comment by dqian-zenefits** [comment]
good point.

*IMO* level funding should use the new pure bs4 vanilla way. and as we move pods out into packages, this should be one of those conversion steps thats necessary (in addition to removing foundation grid references).

one thing to note is, i think for the benefit of the rest of the org...if we want to take into account the overhead it would take engis to learn the nuances of yet another grid system, this may help smooth that over. maybe something we dont care that much about anymore now that we arent growing the eng team like crazy with engis who know nothing about frontend.

**Comment by MiguelMadero** [comment]
Agreed! 

Closings this.

**Pull request closed without merging**
